[clang3.8][forward_list] Compiler error for moving in itself
In file included from /home/travis/build/dubzzz/various-algorithms/containers/forward_list/implem.cpp:123:
/home/travis/build/dubzzz/various-algorithms/containers/forward_list/tests.hpp:362:8: error: explicitly moving variable of type 'forward_list<int>' to itself [-Werror,-Wself-move]
    l2 = std::move(l2);